---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app1-deploy
  labels:
    app: demo-app1-label
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app1-label
  template:
    metadata:
      labels:
        app: demo-app1-label
    spec:
      containers:
        - name: demo-app1-label
          image: mydockeraccfortest/demo_app1:20
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          
---
apiVersion: v1
kind: Service
metadata:
  name: demo-app1-service
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: demo-app1-label
  type: LoadBalancer
